---
agent_list:
        - 10.0.2.85
        - 10.0.2.86
        - 10.0.2.88
        - 10.0.2.131
        - 10.0.2.132
        - 10.0.2.133
bootstrap_url: http://10.0.2.81:5000
cluster_name: DC/OS
exhibitor_storage_backend: static
ip_detect_path: genconf/ip-detect
master_discovery: static
master_list:
        - 10.0.2.82
        - 10.0.2.83
        - 10.0.2.84
process_timeout: 7200
enable_docker_gc: 'true'
enable_gpu_isolation: 'true'
public_agent_list:
        - 10.0.2.87
resolvers:
        - 10.0.2.235
        - 114.114.114.114
ssh_key_path: genconf/ssh_key
ssh_port: 22
ssh_user: core
use_proxy: false
telemetry_enabled: true
oauth_enabled: true
